version: '3'

services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5003:5000"  # First backend instance
    volumes: 
      - ./app:/app
    entrypoint: bash -c "python3 app.py"
    networks:
      - app-network

  backend2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5004:5000"  # Second backend instance
    volumes: 
      - ./app:/app
    entrypoint: bash -c "python3 app.py"
    networks:
      - app-network

  frontend:
    image: httpd:latest
    volumes:
      - ./html:/usr/local/apache2/htdocs/
    ports:
      - "80:80"  # Frontend service remains on port 80
    networks:
      - app-network

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"  # NGINX load balancer on port 8080
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
